steps:

  # build the container image
  - name: gcr.io/cloud-builders/docker
    args: [ build, -t, gcr.io/$PROJECT_ID/gcp-cloudrun-gke-angular, . ]

  # push the container image to Container Registry
  - name: gcr.io/cloud-builders/docker
    args: [ push, gcr.io/$PROJECT_ID/gcp-cloudrun-gke-angular ]

  # Deploy container image to Cloud Run
  - name: gcr.io/cloud-builders/gcloud
    args: [ 'config', 'set', 'compute/zone', 'us-central1-a']
  - name: gcr.io/cloud-builders/gcloud
    args: [ 'compute', 'instances', 'update-container', 'gke-cloudrun-angular-clu-default-pool-2a2063e4-gvdq' , '--container-image', 'gcr.io/$PROJECT_ID/gcp-cloudrun-gke-angular:latest']
    
  - name: gcr.io/cloud-builders/gcloud
    args: [ 'compute', 'instances', 'update-container', 'gke-cloudrun-angular-clu-default-pool-2a2063e4-hvbr' , '--container-image', 'gcr.io/$PROJECT_ID/gcp-cloudrun-gke-angular:latest']
    
  - name: gcr.io/cloud-builders/gcloud
    args: [ 'compute', 'instances', 'update-container', 'gke-cloudrun-angular-clu-default-pool-2a2063e4-x71x' , '--container-image', 'gcr.io/$PROJECT_ID/gcp-cloudrun-gke-angular:latest']
    
  - name: gcr.io/cloud-builders/gcloud
    args: [ beta, run, deploy, gcp-cloudrun-gke-angular, --image, gcr.io/$PROJECT_ID/gcp-cloudrun-gke-angular, --platform, gke, --cluster, cloudrun-angular-cluster]
  

images:

- gcr.io/$PROJECT_ID/gcp-cloudrun-gke-angular
